### ISSUE TITLE
LPBA40 dataSet

### ISSUE THREAD

**Issue by JXT210** [CJSOrange/DMR-Deformer#1]
hello, writer. this LPBA40 dataSet should be divided into 28, 3 and 8 scans for training, val-
idation and testing, respectively.

**Comment by CJSOrange** [comment]
Thanks for your question! We are sorry for this mistake in the article. Actually，the LPBA40 dateset is divided into 30 (train set) and 10 scans (test set). In the train set, the last three scans in numbered order are for validation. While, in the test set, we select the first scan in numbered order as the atlas. 
    So, this LPBA40 dataset is divided into 27, 3 and 10 scans for training, validation and testing, respectively. Neurite-OASIS follows the same partitioning rules. Please add val set as described above and change the dataset path in 'train.py' to see the validation performance during the training phase.

**Comment by CJSOrange** [comment]
Thanks for your question! We are sorry for this mistake in the article. Actually，the LPBA40 dateset is divided into 30 (train set) and 10 scans (test set). In the train set, the last three scans in numbered order are for validation. While, in the test set, we select the first scan in numbered order as the atlas. 

So, this LPBA40 dataset is divided into 27, 3 and 10 scans for training, validation and testing, respectively. Neurite-OASIS follows the same partitioning rules. Please add val set as described above and change the dataset path in 'train.py' to see the validation performance during the training phase.

**Comment by JXT210** [comment]
Thank you very much for your reply.
